# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "machida"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://machida.github.io/"
tags = []
features = []
min_version = "0.01"

[author]
  name = "machida"
  homepage = "https://machida.github.io/"
